language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
